version: '2'

services:
  # Nginx webserver to serve the requests
  homepage_nginx:
    domainname: homepage.test
    image: nginx:alpine
    container_name: homepage_nginx
    ports:
      - "80:80"
    volumes_from:
      - homepage_application
    volumes:
      - ./Docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - homepage-network

  # PHP FPM to run the Laravel Application
  homepage_application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homepage_php
    working_dir: /code
    volumes:
      - .:/code:cached
    networks:
      - homepage-network

  # MySQL database for development
  homepage_mysql:
    image: mysql:5.7.22
    container_name: homepage_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
#      - mysql-storage:/var/lib/mysql/
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - homepage-network

  homepage_redis:
    image: redis:5.0.7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: homepage_redis
    container_name: homepage_redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    networks:
      - homepage-network
    volumes:
#      - redis-storage:/data
      - ./Docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

# Network for the laravel application
networks:
  homepage-network:
    driver: bridge

# Volume for mysql database to persist the data we use after boots.
#volumes:
#  mysql-storage:
#    driver: local
#  redis-storage:
#    driver: local
